//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdCLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hdCLIENTE()
        {
            this.hdDEPTO = new HashSet<hdDEPTO>();
            this.hdSLA = new HashSet<hdSLA>();
            this.hdTICKET = new HashSet<hdTICKET>();
            this.hdTIPO = new HashSet<hdTIPO>();
            this.hdUSUARIO = new HashSet<hdUSUARIO>();
            this.hdSUCURSAL = new HashSet<hdSUCURSAL>();
            this.hdPARAM = new HashSet<hdPARAM>();
        }
    
        public int IDCLIENTE { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string RFC { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<int> DIASCREDITO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public Nullable<System.DateTime> FECHAMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdDEPTO> hdDEPTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdSLA> hdSLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKET> hdTICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTIPO> hdTIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdUSUARIO> hdUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdSUCURSAL> hdSUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdPARAM> hdPARAM { get; set; }
    }
}
