//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdSLA
    {
        public int IDSLA { get; set; }
        public int IDCLIENTE { get; set; }
        public int IDPRIORIDAD { get; set; }
        public int RESPONDEREN { get; set; }
        public int RESOLVEREN { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual hdCLIENTE hdCLIENTE { get; set; }
    }
}
