//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdTICKETDET
    {
        public int IDTICKETDET { get; set; }
        public string IDTICKET { get; set; }
        public int IDCLIENTE { get; set; }
        public string IDUSUARIO { get; set; }
        public string DESCTICKETDET { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual hdTICKET hdTICKET { get; set; }
    }
}
