//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdTICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hdTICKET()
        {
            this.hdTICKETDET = new HashSet<hdTICKETDET>();
            this.hdTICKETDETFILE = new HashSet<hdTICKETDETFILE>();
            this.hdTICKETFILE = new HashSet<hdTICKETFILE>();
            this.hdTICKETTASK = new HashSet<hdTICKETTASK>();
        }
    
        public string IDTICKET { get; set; }
        public int IDCLIENTE { get; set; }
        public int IDTIPO { get; set; }
        public string IDUSUARIO { get; set; }
        public string ASUNTO { get; set; }
        public string DESCTICKET { get; set; }
        public string ESTATUS { get; set; }
        public string ASIGNADOA { get; set; }
        public int IDPRIORIDAD { get; set; }
        public int ORIGEN { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual hdCLIENTE hdCLIENTE { get; set; }
        public virtual hdTIPO hdTIPO { get; set; }
        public virtual hdUSUARIO hdUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKETDET> hdTICKETDET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKETDETFILE> hdTICKETDETFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKETFILE> hdTICKETFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKETTASK> hdTICKETTASK { get; set; }
    }
}
