//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hdUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hdUSUARIO()
        {
            this.hdTICKET = new HashSet<hdTICKET>();
            this.hdTICKET1 = new HashSet<hdTICKET>();
        }
    
        public string IDUSUARIO { get; set; }
        public int IDCLIENTE { get; set; }
        public string IDSUCURSAL { get; set; }
        public int IDDEPTO { get; set; }
        public string NOMUSUARIO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public string PASSW { get; set; }
        public string ROL { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public Nullable<System.DateTime> FECHAMOD { get; set; }
    
        public virtual hdCLIENTE hdCLIENTE { get; set; }
        public virtual hdDEPTO hdDEPTO { get; set; }
        public virtual hdSUCURSAL hdSUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKET> hdTICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hdTICKET> hdTICKET1 { get; set; }
    }
}
