//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helpDeskAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQuantusEntities : DbContext
    {
        public dbQuantusEntities()
            : base("name=dbQuantusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hdCLIENTE> hdCLIENTE { get; set; }
        public virtual DbSet<hdDEPTO> hdDEPTO { get; set; }
        public virtual DbSet<hdSLA> hdSLA { get; set; }
        public virtual DbSet<hdSUCURSAL> hdSUCURSAL { get; set; }
        public virtual DbSet<hdTICKET> hdTICKET { get; set; }
        public virtual DbSet<hdTICKETDET> hdTICKETDET { get; set; }
        public virtual DbSet<hdTICKETDETFILE> hdTICKETDETFILE { get; set; }
        public virtual DbSet<hdTICKETFILE> hdTICKETFILE { get; set; }
        public virtual DbSet<hdTICKETTASK> hdTICKETTASK { get; set; }
        public virtual DbSet<hdTIPO> hdTIPO { get; set; }
        public virtual DbSet<hdUSUARIO> hdUSUARIO { get; set; }
    }
}
